add: MarshalJSON methods for *Array and *Document
FerretDB/wire pull request #70
Opened 2024-12-18 09:49 UTC by KrishnaSindhur

2024-12-18 10:09 UTC, AlekSi requested changes

2024-12-18 10:09 UTC, AlekSi commented on wirebson/document.go
> +	return json.Marshal(jsonMap)
BSON documents are ordered. Converting them to JSON should preserve the order.

2024-12-19 06:18 UTC, AlekSi reviewed
Please also run linters locally

2024-12-19 06:18 UTC, AlekSi commented on wirebson/array.go
> +	}
Let's use `must.NotBeZero(arr)` as in other functions

2024-12-19 06:18 UTC, AlekSi commented on wirebson/array_test.go
Please update tests, benchmarks, and fuzzing in bson_test.go instead

2024-12-19 06:18 UTC, AlekSi commented on wirebson/document.go
> +	jsonObject = append(jsonObject, '{')
```suggestion
	res := []byte{'{'}
```

2024-12-19 06:53 UTC, KrishnaSindhur commented on wirebson/document.go
> +	jsonObject = append(jsonObject, '{')
@AlekSi any changes required here?

2024-12-19 07:17 UTC, AlekSi commented on wirebson/document.go
> +	jsonObject = append(jsonObject, '{')
Well, yeah, I even wrote them

2024-12-19 07:39 UTC, AlekSi commented on wirebson/array_test.go
Please don't resolve conversations. Please also _update_ existing tests/benchmarks/fuzzes, not add new ones.

2024-12-19 07:40 UTC, AlekSi commented on wirebson/document.go
> +	jsonObject = append(jsonObject, '{')
I'm not sure why this conversation was resolved without changing applied

2024-12-19 07:42 UTC, AlekSi reviewed
Review comments were "resolved", but not addressed

2024-12-19 08:28 UTC, KrishnaSindhur commented on wirebson/document.go
> +	jsonObject = append(jsonObject, '{')
I have not added test for error scenarios In MarshalJSON is it ok? Because I don't see any error scenarios tests added for encode functions also!! Please correct me if I am wrong. If necessary I can add test for error scenarios.

2024-12-19 08:40 UTC, AlekSi commented on wirebson/document.go
> +	jsonObject = append(jsonObject, '{')
This comment does not belong to this conversation, where I asked you to replace `make`+`append` combo with a single assignment, and even provided a [suggested change](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request)

2024-12-19 08:54 UTC, KrishnaSindhur commented on wirebson/document.go
> +	jsonObject = append(jsonObject, '{')
Sorry but I can't see your comments you added to replace `make`+`append` to single line, Which ended with so some confusions.

2024-12-19 09:08 UTC, AlekSi requested changes

2024-12-19 09:08 UTC, AlekSi commented on wirebson/bson_test.go
> +			t.Run("ArrayMarshalJSON", func(t *testing.T) {
There is no point in running those subtests for each `tc` with the same input and expected output. Instead, all subtests use `tc`.

Please slow down, check all tests in this file, and make sure your changes follow its structure.

2024-12-20 07:51 UTC, AlekSi requested changes

2024-12-20 07:51 UTC, AlekSi commented on wirebson/bson_test.go
> +var marshalJSONTestCases = []normalTestCase{
Please update existing `normalTestCases` variable instead

2024-12-23 09:28 UTC, AlekSi requested changes
The main comment: please follow the existing code (and tests) structure

2024-12-23 09:28 UTC, AlekSi commented on wirebson/array_test.go
> +		assert.JSONEq(t, expected, string(data))
`assert.JSONEq`, per its documentation, ignores the filed order – something we care about.

I'm also not sure why we have that test at all, given that bson_test.go should already test it.

2024-12-23 09:28 UTC, AlekSi commented on wirebson/bson_test.go
> +	isMarshalJSON bool // isMarshalJSON: Set to true if the test case is meant for JSON marshalling.
_All_ tests should be meant for JSON marshaling and unmarshalling.

Check how `mi`, `doc`, and `raw` are used. Add another field that would contain expected JSON representation and test both decoding and encoding.

2024-12-23 09:28 UTC, AlekSi commented on wirebson/bson_test.go
> +	},
Please update existing test cases (I said that before, didn't I?), not add new ones. Please do not try different ways of adding only a few tests instead of updating existing ones.

2024-12-23 09:28 UTC, AlekSi commented on wirebson/bson_test.go
> +			if tc.raw != nil {
Please revert that change

2024-12-23 09:28 UTC, AlekSi commented on wirebson/document.go
> +// It converts the Document into a JSON object representation while preserving the order of fields.
Note the format of comments for methods that implement the interface and do the same.

2024-12-25 12:24 UTC, closed without merging

2024-12-25 12:24 UTC, AlekSi commented
I made nessisary changes in #71. Thank you!